### ISSUE TITLE
存在系统代理时表情包功能异常

### ISSUE THREAD

**Issue by benx1n** [azmiao/uma_plugin#10]
![image](https://user-images.githubusercontent.com/48101337/160328786-059583a8-a6e4-480c-82ea-003ab5cf1b93.png)
看了一下log，下载那一步抛了异常，应该是代理的问题，关闭后能正常下载

**Comment by azmiao** [comment]
ssl问题，确实是代理，所以强烈建议不要开系统代理，否则其他插件也可能出现问题，一般建议只开pac模式，不改变系统代理，这样需要设置代理的插件就走代理，不需要的就不会走代理

**Comment by azmiao** [comment]
你这样的话，所有不需要代理的插件的所有请求应该都得换成proxies = {}

**Comment by benx1n** [comment]
确实是这样的，之前的插件基本都有配置proxy，所以习惯是全局代理接管再走规则分流2333
那我先关掉这个issue啦
