### ISSUE TITLE
当前APIKEY写到了APIKEY.txt文件内，但是bot的提示信息仍为更改spider.py文件

### ISSUE THREAD

**Issue by jiuma** [azmiao/uma_plugin#14]
呆唯，我来用马娘插件了，apikey根本不在spider.py，你搁哪呢？
![image](https://user-images.githubusercontent.com/41711347/163323706-b2867a33-c059-43bd-b121-32cf82d0e092.png)
![image](https://user-images.githubusercontent.com/41711347/163323815-7e61d335-2fbf-4d49-865a-e2570a831d55.png)

**Comment by azmiao** [comment]
那个提示忘记改了，确实是写到txt里就行了，写进去记得重启hoshino
