### ISSUE TITLE
python-Levenshtein这个依赖安装不了 然后不知道是不是这个原因插件里功能都不能用了 删了重新拉一份也是

### ISSUE THREAD

**Issue by dreamerMJJ** [azmiao/uma_plugin#20]
![image](https://user-images.githubusercontent.com/92427687/166899953-8c326c5a-972f-4238-a7ed-c70bcf9aada0.png)
顺便大佬有没有QQ群什么的，想找个方便的地方学学经验

**Comment by azmiao** [comment]
这个依赖装不了的话就把requirements.txt这一行删了，再重新安装依赖，这个依赖不是必要的，用于提速的。另外我没有群23333

**Comment by dreamerMJJ** [comment]
试过了 但功能还是都报错
![image](https://user-images.githubusercontent.com/92427687/166902976-e354731e-20b1-43fb-9db4-57640d66ef6a.png)
![image](https://user-images.githubusercontent.com/92427687/166903056-7c039852-9856-4301-8b24-f493caedb284.png)

**Comment by azmiao** [comment]
> 试过了 但功能还是都报错 ![image](https://user-images.githubusercontent.com/92427687/166902976-e354731e-20b1-43fb-9db4-57640d66ef6a.png) ![image](https://user-images.githubusercontent.com/92427687/166903056-7c039852-9856-4301-8b24-f493caedb284.png)

那你数据更新完了么？

**Comment by azmiao** [comment]
> > 试过了 但功能还是都报错 ![image](https://user-images.githubusercontent.com/92427687/166902976-e354731e-20b1-43fb-9db4-57640d66ef6a.png) ![image](https://user-images.githubusercontent.com/92427687/166903056-7c039852-9856-4301-8b24-f493caedb284.png)
> 
> 那你数据更新完了么？

现在更新至2.0.1后更新应该很快了，大概

**Comment by azmiao** [comment]
反正我感觉这个问题重启一下hoshino就能解决（）

**Comment by dreamerMJJ** [comment]
> 反正我感觉这个问题重启一下hoshino就能解决（）

试过了 没用呢  手功更新命令机器人是秒回复失败的 然后控制台就上面截图的那些

**Comment by azmiao** [comment]
> > 反正我感觉这个问题重启一下hoshino就能解决（）
> 
> 试过了 没用呢 手功更新命令机器人是秒回复失败的 然后控制台就上面截图的那些

请问机器人回复更新失败有其他内容吗

**Comment by dreamerMJJ** [comment]
> 
![image](https://user-images.githubusercontent.com/92427687/166914221-50ed1866-08de-4128-a541-0ed48d7ffb0b.png)
这个截图回答了你的问题顺便又发现了个新问题（

**Comment by azmiao** [comment]
> > 反正我感觉这个问题重启一下hoshino就能解决（）
> 
> 试过了 没用呢 手功更新命令机器人是秒回复失败的 然后控制台就上面截图的那些

哦对了，可以尝试把uma_plugin/uma_info/config.json 和 hoshinobot/res/img/umamusume文件夹整个删了再重启hoshino试试

**Comment by dreamerMJJ** [comment]
> > > 反正我感觉这个问题重启一下hoshino就能解决（）
> > 
> > 
> > 试过了 没用呢 手功更新命令机器人是秒回复失败的 然后控制台就上面截图的那些
> 
> 哦对了，可以尝试把uma_plugin/uma_info/config.json 和 hoshinobot/res/img/umamusume文件夹整个删了再重启hoshino试试

![image](https://user-images.githubusercontent.com/92427687/166914864-f88170c2-164a-42a5-a3b8-e2d41deab731.png)
![image](https://user-images.githubusercontent.com/92427687/166915052-92b548c7-33c7-4949-a066-68c54ede1fa0.png)
按你说的尝试了下

**Comment by azmiao** [comment]
> > > > 反正我感觉这个问题重启一下hoshino就能解决（）
> > > 
> > > 
> > > 试过了 没用呢 手功更新命令机器人是秒回复失败的 然后控制台就上面截图的那些
> > 
> > 
> > 哦对了，可以尝试把uma_plugin/uma_info/config.json 和 hoshinobot/res/img/umamusume文件夹整个删了再重启hoshino试试
> 
> ![image](https://user-images.githubusercontent.com/92427687/166914864-f88170c2-164a-42a5-a3b8-e2d41deab731.png) ![image](https://user-images.githubusercontent.com/92427687/166915052-92b548c7-33c7-4949-a066-68c54ede1fa0.png) 按你说的尝试了下

首先数据没更新完，下面几个功能都是不能用的，所以问题就在你这更新报错上，但你这报错就很奇怪233333

**Comment by dreamerMJJ** [comment]
> > > > > 反正我感觉这个问题重启一下hoshino就能解决（）
> > > > 
> > > > 
> > > > 试过了 没用呢 手功更新命令机器人是秒回复失败的 然后控制台就上面截图的那些
> > > 
> > > 
> > > 哦对了，可以尝试把uma_plugin/uma_info/config.json 和 hoshinobot/res/img/umamusume文件夹整个删了再重启hoshino试试
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/92427687/166914864-f88170c2-164a-42a5-a3b8-e2d41deab731.png) ![image](https://user-images.githubusercontent.com/92427687/166915052-92b548c7-33c7-4949-a066-68c54ede1fa0.png) 按你说的尝试了下
> 
> 首先数据没更新完，下面几个功能都是不能用的，所以问题就在你这更新报错上，但你这报错就很奇怪233333

上一次更新是出了查技能哪个版本  虽然不知道为什么查技能用不了然后一直懒得找原因。。  然后今天放完假第一天上班开开心心摸鱼更新一波机器人然后就不能用了 很绝望（

**Comment by azmiao** [comment]
你把uma_info文件夹里 的 `spider.py`里的第11行到第28行替换成这个再重启机器人看看报什么错：
```
async def update():
    if not os.path.exists(current_dir):
        logger.info('====未检测到马娘数据库文件，正在开始创建文件和更新信息====')
        init_data = {}
        with open(current_dir, 'w', encoding='UTF-8') as f:
        json.dump(init_data, f, indent=4, ensure_ascii=False)
        await uma_update(current_dir)
        logger.info('====马娘数据库更新完成====')
    return True
```

**Comment by dreamerMJJ** [comment]
> 你把uma_info文件夹里 的 `spider.py`里的第11行到第28行替换成这个再重启机器人看看报什么错：
> 
> ```
> async def update():
>     if not os.path.exists(current_dir):
>         logger.info('====未检测到马娘数据库文件，正在开始创建文件和更新信息====')
>         init_data = {}
>         with open(current_dir, 'w', encoding='UTF-8') as f:
>         json.dump(init_data, f, indent=4, ensure_ascii=False)
>         await uma_update(current_dir)
>         logger.info('====马娘数据库更新完成====')
>     return True
> ```


![image](https://user-images.githubusercontent.com/92427687/166917847-6c2149b1-3335-47d2-b8d6-db570b51dd94.png)
![image](https://user-images.githubusercontent.com/92427687/166917922-887c7504-62c2-4641-ad76-ebf4c9b6d571.png)
替换前与替换后  是这样么  怎么感觉不太对

**Comment by azmiao** [comment]
> > 你把uma_info文件夹里 的 `spider.py`里的第11行到第28行替换成这个再重启机器人看看报什么错：
> > ```
> > async def update():
> >     if not os.path.exists(current_dir):
> >         logger.info('====未检测到马娘数据库文件，正在开始创建文件和更新信息====')
> >         init_data = {}
> >         with open(current_dir, 'w', encoding='UTF-8') as f:
> >         json.dump(init_data, f, indent=4, ensure_ascii=False)
> >         await uma_update(current_dir)
> >         logger.info('====马娘数据库更新完成====')
> >     return True
> > ```
> 
> ![image](https://user-images.githubusercontent.com/92427687/166917847-6c2149b1-3335-47d2-b8d6-db570b51dd94.png) ![image](https://user-images.githubusercontent.com/92427687/166917922-887c7504-62c2-4641-ad76-ebf4c9b6d571.png) 替换前与替换后 是这样么 怎么感觉不太对

不是不是，我的错，说错了不是这个文件23333，是`update_init.py`

**Comment by dreamerMJJ** [comment]
> 不是不是，我的错，说错了不是这个文件23333，是`update_init.py`

![image](https://user-images.githubusercontent.com/92427687/166921875-58c3d675-75b4-4d39-b194-a25fdb811fe0.png)
![image](https://user-images.githubusercontent.com/92427687/166921923-bfdada21-a6da-420a-9557-4ff8acb8fdf1.png)
刚刚才注意到有这个报错  然后查了一下是我拉取代码有问题吗？  可是其他模块都加载成功了

**Comment by dreamerMJJ** [comment]
> > 不是不是，我的错，说错了不是这个文件23333，是`update_init.py`
> 
> ![image](https://user-images.githubusercontent.com/92427687/166921875-58c3d675-75b4-4d39-b194-a25fdb811fe0.png) ![image](https://user-images.githubusercontent.com/92427687/166921923-bfdada21-a6da-420a-9557-4ff8acb8fdf1.png) 刚刚才注意到有这个报错 然后查了一下是我拉取代码有问题吗？ 可是其他模块都加载成功了

![image](https://user-images.githubusercontent.com/92427687/166922135-8ddfdbb9-83fb-4fb9-ab7a-26482be07a46.png)

**Comment by azmiao** [comment]
环境变量没配置好，看这里电线佬的回复 https://github.com/azmiao/uma_plugin/issues/17

**Comment by dreamerMJJ** [comment]
> 环境变量没配置好，看这里电线佬的回复 #17

搞了一下 然后又重启了服务器 手动更新显示是成功的 但功能还是用不了 控制台现在还有着这样的问题
![image](https://user-images.githubusercontent.com/92427687/166926756-dcc18a04-3530-4a62-a580-6fbf894378a4.png)

**Comment by azmiao** [comment]
> > 环境变量没配置好，看这里电线佬的回复 #17
> 
> 搞了一下 然后又重启了服务器 手动更新显示是成功的 但功能还是用不了 控制台现在还有着这样的问题 ![image](https://user-images.githubusercontent.com/92427687/166926756-dcc18a04-3530-4a62-a580-6fbf894378a4.png)

这时候在吧uma_plugin/uma_info/config.json 和 hoshinobot/res/img/umamusume文件夹整个删了再重启hoshino试试

**Comment by dreamerMJJ** [comment]
> 

试了 没变化  Service name "uma_help" already exist!  看着好像很简单的问题  要是我懂一点python是不是就能自己改了（

**Comment by dreamerMJJ** [comment]
> 

![image](https://user-images.githubusercontent.com/92427687/166929767-32097240-3347-4442-9c66-2a2d5092a75f.png)
这个error是个吉兆是什么鬼

**Comment by azmiao** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/92427687/166929767-32097240-3347-4442-9c66-2a2d5092a75f.png) 这个error是个吉兆是什么鬼

因为马娘里新加了吉兆（），数据库里我应该也加了啊2333

**Comment by azmiao** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/92427687/166929767-32097240-3347-4442-9c66-2a2d5092a75f.png) 这个error是个吉兆是什么鬼
> 
> 因为马娘里新加了吉兆（），数据库里我应该也加了啊2333

所以讲道理删除那俩重新启动应该就会更新了

**Comment by dreamerMJJ** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/92427687/166929767-32097240-3347-4442-9c66-2a2d5092a75f.png) 这个error是个吉兆是什么鬼
> > 
> > 
> > 因为马娘里新加了吉兆（），数据库里我应该也加了啊2333
> 
> 所以讲道理删除那俩重新启动应该就会更新了
我顺蔓摸瓜在hoshino\modules\uma_plugin\uma_info里 加进了
"symbolikriss": [],
"taninogimlet": [] 
然后查角色信息之类的就能用了2333

**Comment by dreamerMJJ** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/92427687/166929767-32097240-3347-4442-9c66-2a2d5092a75f.png) 这个error是个吉兆是什么鬼
> > > > 
> > > > 
> > > > 因为马娘里新加了吉兆（），数据库里我应该也加了啊2333
> > > 
> > > 
> > > 所以讲道理删除那俩重新启动应该就会更新了
> > > 我顺蔓摸瓜在hoshino\modules\uma_plugin\uma_info\replace_dict.json里 加进了
> > > "symbolikriss": [],
> > > "taninogimlet": []
> > > 然后查角色信息之类的就能用了2333
> 
> 话说你插件版本更新了嘛，我今晚刚更新了吉兆和谷野美酒

是的我刚看见那个2小时前的提交 一直在尝试改没看到。。

**Comment by dreamerMJJ** [comment]
删了重新拉了下代码  然后试了试  其他功能都可以了 只有节奏榜用不了。。
![image](https://user-images.githubusercontent.com/92427687/166941047-10c86ddd-4da6-4395-b340-a85a97453729.png)

**Comment by azmiao** [comment]
> 

把你uma_plugin\uma_support_chart下的那个json文件删了再重启机器人

**Comment by azmiao** [comment]
> > 
> 
> 不太行的样子 查询命令不管哪个都是一直：配置文件内未找到速卡节奏榜相关配置，现已成功创建 INFO: 速卡节奏榜有更新，正在替换旧版文件 然后系统找不到指定的路径

现在再更新一下插件试一下吧，之前更新2.0.0的时候更出的BUG，一直没注意到，刚刚修复了（大概

**Comment by dreamerMJJ** [comment]
> > > 
> > 
> > 
> > 不太行的样子 查询命令不管哪个都是一直：配置文件内未找到速卡节奏榜相关配置，现已成功创建 INFO: 速卡节奏榜有更新，正在替换旧版文件 然后系统找不到指定的路径
> 
> 现在再更新一下插件试一下吧，之前更新2.0.0的时候更出的BUG，一直没注意到，刚刚修复了（大概

![image](https://user-images.githubusercontent.com/92427687/166950200-3f27524e-cfed-4697-8222-dfe67f7420ec.png)

虽然能用了 但是（

**Comment by azmiao** [comment]
> > > > 
> > > 
> > > 
> > > 不太行的样子 查询命令不管哪个都是一直：配置文件内未找到速卡节奏榜相关配置，现已成功创建 INFO: 速卡节奏榜有更新，正在替换旧版文件 然后系统找不到指定的路径
> > 
> > 
> > 现在再更新一下插件试一下吧，之前更新2.0.0的时候更出的BUG，一直没注意到，刚刚修复了（大概
> 
> ![image](https://user-images.githubusercontent.com/92427687/166950200-3f27524e-cfed-4697-8222-dfe67f7420ec.png)
> 
> 虽然能用了 但是（

奇怪了，我无论怎么用全新环境安装测试都遇不到你这问题，要不截图看看sup_config.json的内容？

**Comment by dreamerMJJ** [comment]
![image](https://user-images.githubusercontent.com/92427687/166952396-177972f1-14d0-413e-882a-c0c1a4ca8206.png)
以为又是我的问题 打算删了再试一下  但是删完重启的和删之前的一样都是这样

**Comment by azmiao** [comment]
哦，我去，刚刚改错东西了，抱歉，你再更新一下插件试试，刚刚眼花了改错代码了

**Comment by azmiao** [comment]
> 

问题能解决了就好2333，反正我大赛摸鱼hhh

**Comment by dreamerMJJ** [comment]
> 问题能解决了就好2333，反正我大赛摸鱼hhh

大佬最近还有在做什么新功能吗，能不能提前说说期待下

**Comment by azmiao** [comment]
> > 问题能解决了就好2333，反正我大赛摸鱼hhh
> 
> 大佬最近还有在做什么新功能吗，能不能提前说说期待下

暂时没有，最近在忙，忙完可能会再看看加点啥功能
