### ISSUE TITLE
马娘数据库更新失败：Cmd('git') failed due to: exit code(128)

### ISSUE THREAD

**Issue by Qielanyinyin** [azmiao/uma_plugin#21]
[2022-05-09 23:06:31,768 hoshino] INFO: ====未检测到马娘数据库文件，正在开始创建文件和更新信息====
[2022-05-09 23:06:31,768 hoshino] INFO: 正在更新数据至最新，请耐心等待，预计用时1分钟
[2022-05-09 23:06:32,299 hoshino] INFO: ====马娘数据库更新失败：Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=main https://api.mtr.pub/azmiao/uma_info_data.git C:/Resources/img\umamusume\base_data/
  stderr: 'Cloning into 'C:/Resources/img\umamusume\base_data'...
fatal: unable to access 'https://api.mtr.pub/azmiao/uma_info_data.git/': OpenSSL SSL_connect: Connection was reset in connection to api.mtr.pub:443
'。已回退====
[2022-05-09 23:06:32,299 hoshino] INFO: 马娘基础数据库更新失败，后续更新操作已停止，请重新启动Bot更新

**Comment by Qielanyinyin** [comment]
> 那请问现在可以运行了吗

不行。
另外我试了下重置DNS也不行

**Comment by Qielanyinyin** [comment]
> > > 那请问现在可以运行了吗
> > 
> > 不行。 另外我试了下重置DNS也不行
> 
> 移除ssl验证也不行吗，我这边自己的电脑倒是装完git就直接移除验证了，另外实在不行试试百度谷歌一下吧？

嗯，我有时间自己百度下吧

**Comment by azmiao** [comment]
https://blog.csdn.net/qq_37555071/article/details/114260533
虽然是垃圾CSDN但可以试试23333
![image](https://user-images.githubusercontent.com/54100327/167594003-0ca46e9d-69cc-485c-a81e-62cc6844b36a.png)

**Comment by Qielanyinyin** [comment]
已解决：
开始以为是https://api.mtr.pub/azmiao/uma_info_data.git连不上，于是改成了https://github.com/azmiao/uma_info_data.git
显示错误：error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
然后百度了下，用了以下命令：
git config http.sslVerify "false"
git config --global http.sslVerify "false"

git config --global http.postBuffer 524288000
然后重启bot就可以了。
感觉关键是最后一步。服务器容量小，默认本地仓库文件大小上限太小了，不能正常写入，改了上限就可以写入了。不知道是不是这个原因。

**Comment by azmiao** [comment]
> 已解决： 开始以为是[https://api.mtr.pub/azmiao/uma_info_data.git连不上，于是改成了https://github.com/azmiao/uma_info_data.git](https://api.mtr.pub/azmiao/uma_info_data.git%E8%BF%9E%E4%B8%8D%E4%B8%8A%EF%BC%8C%E4%BA%8E%E6%98%AF%E6%94%B9%E6%88%90%E4%BA%86https://github.com/azmiao/uma_info_data.git) 显示错误：error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054 然后百度了下，用了以下命令： git config http.sslVerify "false" git config --global http.sslVerify "false"
> 
> git config --global http.postBuffer 524288000 然后重启bot就可以了。 感觉关键是最后一步。服务器容量小，默认本地仓库文件大小上限太小了，不能正常写入，改了上限就可以写入了。不知道是不是这个原因。

哦，原来如此，虽然不知道文件上限多大，但其实那个仓库只有32MB我感觉也不是特别大2333，另外能解决就好
