### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by int-PP** [azmiao/uma_plugin#23]
没错又是我hhh，新闻翻译建议加个合并转发，超过1000字太长的可以拆开来进行多条合并转发

**Comment by azmiao** [comment]
> 没错又是我hhh，新闻翻译建议加个合并转发，超过1000字太长的可以拆开来进行多条合并转发

合并转发可以是可以但不是很必要，因为总共就一条消息。另外那个1000字限制不是因为太长发不出来，而是因为太长了无法翻译233333

**Comment by azmiao** [comment]
哦，你的意思莫非是把正常的新闻翻译拆成几个短的转发消息发吗

**Comment by int-PP** [comment]
> > 没错又是我hhh，新闻翻译建议加个合并转发，超过1000字太长的可以拆开来进行多条合并转发
> 
> 合并转发可以是可以但不是很必要，因为总共就一条消息。另外那个1000字限制不是因为太长发不出来，而是因为太长了无法翻译233333

我还以为是太长了发不出来hhh，不过有时候很长的新闻还带个图好大一坨能直接刷屏了。有时候新闻翻译还会显示正在龟速翻译但是不返回翻译内容。

**Comment by azmiao** [comment]
> > > 没错又是我hhh，新闻翻译建议加个合并转发，超过1000字太长的可以拆开来进行多条合并转发
> > 
> > 
> > 合并转发可以是可以但不是很必要，因为总共就一条消息。另外那个1000字限制不是因为太长发不出来，而是因为太长了无法翻译233333
> 
> 我还以为是太长了发不出来hhh，不过有时候很长的新闻还带个图好大一坨能直接刷屏了。有时候新闻翻译还会显示正在龟速翻译但是不返回翻译内容。

那我待会就把内容全放到转发消息里吧，另外翻译发不出来可能是消息被风控了，另外其实转发消息更容易风控（

**Comment by int-PP** [comment]
> > > > 没错又是我hhh，新闻翻译建议加个合并转发，超过1000字太长的可以拆开来进行多条合并转发
> > > 
> > > 
> > > 合并转发可以是可以但不是很必要，因为总共就一条消息。另外那个1000字限制不是因为太长发不出来，而是因为太长了无法翻译233333
> > 
> > 
> > 我还以为是太长了发不出来hhh，不过有时候很长的新闻还带个图好大一坨能直接刷屏了。有时候新闻翻译还会显示正在龟速翻译但是不返回翻译内容。
> 
> 那我待会就把内容全放到转发消息里吧，另外翻译发不出来可能是消息被风控了，另外其实转发消息更容易风控（

转发更容易么?(  加个合并转发开关觉得好点吧
![image](https://user-images.githubusercontent.com/105854929/174478771-f7df24db-c7e0-4483-874a-ad71b26ba913.png)

**Comment by azmiao** [comment]
> > > > > 没错又是我hhh，新闻翻译建议加个合并转发，超过1000字太长的可以拆开来进行多条合并转发
> > > > 
> > > > 
> > > > 合并转发可以是可以但不是很必要，因为总共就一条消息。另外那个1000字限制不是因为太长发不出来，而是因为太长了无法翻译233333
> > > 
> > > 
> > > 我还以为是太长了发不出来hhh，不过有时候很长的新闻还带个图好大一坨能直接刷屏了。有时候新闻翻译还会显示正在龟速翻译但是不返回翻译内容。
> > 
> > 
> > 那我待会就把内容全放到转发消息里吧，另外翻译发不出来可能是消息被风控了，另外其实转发消息更容易风控（
> 
> 转发更容易么?( 加个合并转发开关觉得好点吧 ![image](https://user-images.githubusercontent.com/105854929/174478771-f7df24db-c7e0-4483-874a-ad71b26ba913.png)

嗯嗯，我在加了，issue可以先开着

**Comment by int-PP** [comment]
> > > > > > 没错又是我hhh，新闻翻译建议加个合并转发，超过1000字太长的可以拆开来进行多条合并转发
> > > > > 
> > > > > 
> > > > > 合并转发可以是可以但不是很必要，因为总共就一条消息。另外那个1000字限制不是因为太长发不出来，而是因为太长了无法翻译233333
> > > > 
> > > > 
> > > > 我还以为是太长了发不出来hhh，不过有时候很长的新闻还带个图好大一坨能直接刷屏了。有时候新闻翻译还会显示正在龟速翻译但是不返回翻译内容。
> > > 
> > > 
> > > 那我待会就把内容全放到转发消息里吧，另外翻译发不出来可能是消息被风控了，另外其实转发消息更容易风控（
> > 
> > 
> > 转发更容易么?( 加个合并转发开关觉得好点吧 ![image](https://user-images.githubusercontent.com/105854929/174478771-f7df24db-c7e0-4483-874a-ad71b26ba913.png)
> 
> 嗯嗯，我在加了，issue可以先开着

好的，谢谢大佬
![image](https://user-images.githubusercontent.com/105854929/174478846-72e1a60e-a1b9-462f-ae94-be6a3b19993d.png)
