### ISSUE TITLE
节奏榜图片无法获取

### ISSUE THREAD

**Issue by BossWangST** [azmiao/uma_plugin#24]
bot 的 pip 包都正常安装，且交互成功。但是在节奏榜的功能下，一直无法获取到图片，查看本地目录 supprt_chart 也是空的，不知道是不是网页链接改变了的问题。

截图如下：
![image](https://user-images.githubusercontent.com/53068625/177295249-55d54eaf-4bdb-42ff-b7b7-e5c72967d7df.png)

还请大佬看一下，谢谢！

**Comment by azmiao** [comment]
确实网页有点变化，正在改了

**Comment by BossWangST** [comment]
感谢！

**Comment by azmiao** [comment]
临时修复了下，更新完删除uma_plugin\uma_support_chart目录下的`sup_config.json`再重启hoshino试试，另外这个issue先不要关闭，有空再整整吧，bwiki之前是重定向跳转，现在直接把以前的界面删了，还需要再改改

**Comment by BossWangST** [comment]
看了下，应该是 bwiki 只保留最新的节奏榜界面了，以前的图片都没了；这样的话也许可以考虑每次都先从 bwiki 攻略子页面获取下最新的版本号，然后用这个新版本号比较后直接替换掉新图片的 url，直接获取新图片（个人的简陋思路）。
感谢作者的 bot 插件和教程！

**Comment by azmiao** [comment]
> 

其实一开始就是这样的2333，但那个页面经常不更新，虽然你看到是新的但代码爬到的仍然是缓存的，然后有个节奏榜汇总那个更新的更慢hhhh，我再想点别的办法吧

**Comment by azmiao** [comment]
想了想还是从攻略子界面进入稳定2333，之后再研究研究缓存怎么办吧
