### ISSUE TITLE
有个新功能的想法

### ISSUE THREAD

**Issue by int-PP** [azmiao/uma_plugin#25]
感觉可以增加个赛程的培育目标。
![HO I_ ` OIX)WF4} MXS8Y](https://user-images.githubusercontent.com/105854929/177684746-1dc24bab-113f-4700-981a-ce5e98180038.jpg)
直接参考bwiki的培育目标数据

**Comment by azmiao** [comment]
待更新

**Comment by int-PP** [comment]
![Q4G~O }YCAQ{T{MN RT8JHV](https://user-images.githubusercontent.com/105854929/177709000-d0d2e7b8-1057-4e43-a949-e48d3d0e21f7.jpg)

**Comment by azmiao** [comment]
文件夹已经新建好了，过两天再写，先摸会鱼~
