### ISSUE TITLE
UP池译名与卡池不一致导致图片资源无法对应

### ISSUE THREAD

**Issue by LoveCany** [azmiao/uma_plugin#27]
![BWIKI更新](https://s2.loli.net/2022/07/12/5eNQngWqJ6vDm9w.png)
如上图所示，翻译名在今天经过一次[更新](https://wiki.biligame.com/umamusume/index.php?title=%E7%A9%BA%E4%B8%AD%E7%A5%9E%E5%AE%AB%26%E6%94%AF%E6%8F%B4%E5%8D%A1%E5%8D%A1%E6%B1%A0_20220711&type=revision&diff=46779&oldid=46468)，UP池数据在更新后加载（此时译名与卡池未对应），但图片资源名与卡池名对应，会导致无法正确加载图片资源。
![](https://s2.loli.net/2022/07/12/Ikn7Pc6emtyVW2i.png)
是否可以考虑在手动更新/重载卡池时重新抓取BWIKI数据（即使当前UP池未过期），避免上述问题？（虽然我觉得这波是BWIKI编辑全责）

**Comment by azmiao** [comment]
bwiki上的卡尺公告里的同步名称就是我改的2333，面包佬翻译的时候一般wiki图鉴名称还未更新所以是他自己翻译的，然后我一般会在卡池更新前的晚上同步图鉴名称，但昨晚忘了2333.然后因为bwiki的缓存无法强制刷新，即使使用wiki自带的强制刷新也没那么快生效，所以bot爬到的内容会一直保持首次爬到的内容，然后大概过一两天才会更新为最新的内容。另外手动更新/重载卡池时本身就会重新抓取BWIKI数据，但缓存刷新不掉，所以爬到的数据不是最新的，之前也研究了很久怎么让他能爬到最新的，但没整出来。

**Comment by azmiao** [comment]
> 顺便发现了一个奇怪的问题，现在BWIKI的公告已经更正了，但是每次强制更新数据还是会获取到老的译名（无论删掉`pretty_up_char.json`还是手动修改名称），怀疑是海外CDN缓存还没过期

是这样的2333
