### ISSUE TITLE
拉取技能與wiki不一致導致技能查詢結果錯位，同時新增繁中技能查詢

### ISSUE THREAD

**Issue by Yui-xy** [azmiao/uma_plugin#28]
### 修復前
![image](https://user-images.githubusercontent.com/109400934/179337723-b5a97a7d-371b-4fde-8cfe-0bb5141e3070.png)
### 修復后
![image](https://user-images.githubusercontent.com/109400934/179337735-247e8d58-165f-4d27-abad-add7265af4bc.png)
改動代碼
链接：https://pan.baidu.com/s/1GQ49OR3GA_oSQ6Im8DwLqw?pwd=1avm

**Comment by azmiao** [comment]
已同步到主分支，感谢

**Comment by dreamerMJJ** [comment]
更新后查技能出现了这样的问题

**Comment by dreamerMJJ** [comment]
更新后查技能出现了这样的报错
[2022-07-18 09:49:31,977 uma_skills] ERROR: 'tw_name_dict'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\umabot\HoshinoBot-lite-uma\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\umabot\HoshinoBot-lite-uma\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\__init__.py", line 40, in check_skill
    msg = await get_skill_info(skill_name, f_data)
  File "C:\Users\Administrator\Desktop\umabot\HoshinoBot-lite-uma\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\generate.py", line 35, in get_skill_info
    tw_name_dict = f_data['tw_name_dict']
KeyError: 'tw_name_dict'

**Comment by Yui-xy** [comment]
> 更新后查技能出现了这样的报错 [2022-07-18 09:49:31,977 uma_skills] ERROR: 'tw_name_dict' Traceback (most recent call last): File "C:\Users\Administrator\Desktop\umabot\HoshinoBot-lite-uma\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message await service_func.func(bot, event) File "C:\Users\Administrator\Desktop\umabot\HoshinoBot-lite-uma\HoshinoBot\hoshino\modules\uma_plugin\uma_skills__init__.py", line 40, in check_skill msg = await get_skill_info(skill_name, f_data) File "C:\Users\Administrator\Desktop\umabot\HoshinoBot-lite-uma\HoshinoBot\hoshino\modules\uma_plugin\uma_skills\generate.py", line 35, in get_skill_info tw_name_dict = f_data['tw_name_dict'] KeyError: 'tw_name_dict'

可能是定义有缺损吧，我把我的插件整体打包给你
链接：https://pan.baidu.com/s/1bvu626CelX6l6cPrO_dc8A?pwd=yogm 
你对比一下或者整体替换都可以

**Comment by azmiao** [comment]
啊这，待会我有空看一下吧

**Comment by azmiao** [comment]
测试了一下，手动更新一下马娘技能就行了

**Comment by dreamerMJJ** [comment]
工作有点忙忘了这边了。。 确实手动更新马娘技能之后就没问题了
