### ISSUE TITLE
在安装依赖的时候报错，显示版本不匹配

### ISSUE THREAD

**Issue by QiXun2003** [azmiao/uma_plugin#30]
![image](https://user-images.githubusercontent.com/106389705/179612289-d6fa8def-3e9f-438b-be09-e0bd2372fa3a.png)
w我在粘贴上教程中的安装依赖代码之后，弹出了这个报错，请问应该怎么才能解决这个问题呢
![image](https://user-images.githubusercontent.com/106389705/179612544-013cca71-c8f6-4ab4-a924-761aba69f4cb.png)

**Comment by azmiao** [comment]
你可以试试吧requirements.txt中beautifulsoup4改成bs4试试，具体怎么改你也可以百度看看，这种问题偶尔也有人遇到，百度可能是个不错的选择，就把红字部分复制百度一下。顺带问一句你的python版本是多少呢

**Comment by BossWangST** [comment]
看报错信息应该是阿里云的源仓库没有 bs4 的对应版本包，可以尝试 `pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple` 用清华的源来安装

**Comment by azmiao** [comment]
> 看报错信息应该是阿里云的源仓库没有 bs4 的对应版本包，可以尝试 `pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple` 用清华的源来安装

确实，阿里云好像没有这个，更换镜像应该就可以了，清华和华为应该都行

**Comment by QiXun2003** [comment]
> 看报错信息应该是阿里云的源仓库没有 bs4 的对应版本包，可以尝试 `pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple` 用清华的源来安装

我已经解决了问题，非常感谢

**Comment by QiXun2003** [comment]
> > 看报错信息应该是阿里云的源仓库没有 bs4 的对应版本包，可以尝试 `pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple` 用清华的源来安装
> 
> 确实，阿里云好像没有这个，更换镜像应该就可以了，清华和华为应该都行

我已经解决了问题，非常感谢
