### ISSUE TITLE
大大，查技能报错啦~！

### ISSUE THREAD

**Issue by GudaTom** [azmiao/uma_plugin#34]
![image](https://user-images.githubusercontent.com/40374414/181396900-d10d005b-b106-4561-9577-9d7cbb2000cd.png)

**Comment by azmiao** [comment]
尝试一下命令“手动更新马娘技能”，然后无需重启bot直接尝试再次使用命令查技能试试

**Comment by GudaTom** [comment]
> 

可以了！谢谢大大！
