### ISSUE TITLE
刚刚搭建的机器人速卡节奏榜获取出错

### ISSUE THREAD

**Issue by AVRAMAX** [azmiao/uma_plugin#51]
![image](https://user-images.githubusercontent.com/126690548/222171797-1478810c-a404-4de7-9907-062b949ba8ef.png)
麻烦大佬了

**Comment by azmiao** [comment]
这两天新版本更新，节奏榜wiki那边大佬也在更新，所以确实会有报错，部分还没更新完，等那边更新完这边一起修哈

**Comment by azmiao** [comment]
哦但是你这个错误，感觉像是代理配置错误或者httpx版本不对

**Comment by AVRAMAX** [comment]
好的好的我去检查一下谢谢大大

**Comment by azmiao** [comment]
你可以去看看windows系统设置里的代理服务器是不是被你打开了，那个得关掉哦

**Comment by AVRAMAX** [comment]
噗还真是代理服务器的问题，十分感谢
