### ISSUE TITLE
无法加载插件内的各种功能

### ISSUE THREAD

**Issue by HMScygnet** [azmiao/uma_plugin#52]
![G1~3V_9LC}{K ~W1U{(0$BA](https://user-images.githubusercontent.com/65561426/223709666-2df2d748-08c8-4946-b56e-d08a4c4e0875.png)
里面的功能都是这个报错

但是`uma_comic`和`uma_compatibility`成功加载了，看了半天也没看懂为什么会这么报错

**Comment by azmiao** [comment]
你再往上看看，有没有其他报错，可以去日志文件里看一下

**Comment by Baimotong** [comment]
> 

大佬你好，我和他一样也出现了这个问题，今天刚搭的bot
![QQ截图20230308232838](https://user-images.githubusercontent.com/30062345/223756589-22919fa4-6495-45c7-9eb5-c8a64ef97e8f.png)

**Comment by azmiao** [comment]
> > 
> 
> 大佬你好，我和他一样也出现了这个问题，今天刚搭的bot ![QQ截图20230308232838](https://user-images.githubusercontent.com/30062345/223756589-22919fa4-6495-45c7-9eb5-c8a64ef97e8f.png)

下面那些不用看，看第一个就行，因为前面的子模块没起来，后面的也起不来的，看了下wiki上漫画界面雀食变动了，等我修复一下

**Comment by azmiao** [comment]
@Baimotong 最新的commit应该已经修复马娘漫画的问题了 [419207e](https://github.com/azmiao/uma_plugin/commit/419207e48740f06eddab8519070a01a7aef881d7) ，你可以更新一下试试

**Comment by Baimotong** [comment]
> @Baimotong 最新的commit应该已经修复马娘漫画的问题了 [7b50274](https://github.com/azmiao/uma_plugin/commit/7b50274926a3d2e05d472d27d4d4b779421de5c3) ，你可以更新一下试试

可以用了，感谢大佬
