### ISSUE TITLE
抽马娘卡池出现问题

### ISSUE THREAD

**Issue by Baimotong** [azmiao/uma_plugin#53]
![image](https://user-images.githubusercontent.com/30062345/228553194-9c5c0f6f-95f1-424c-bb03-03f51c70be10.png)
今天更新卡池，抽卡功能抽到新马就这样了，支援卡倒是没有问题，请问下大佬应该怎么解决？

**Comment by azmiao** [comment]
随便找个群发一句“更新马娘卡池”，wiki的卡池数据更新没那么快的，你强制手动更新就行

**Comment by Baimotong** [comment]
这个有尝试过的，也重启过bot了，刚试了卸载重装插件还是不行

**Comment by azmiao** [comment]
你现在再“更新马娘卡池”一下试试，刚才我去wiki上看了下赛马娘一览又没人刷新2333，刚刚我在wiki手动刷新了一下

**Comment by Baimotong** [comment]
可以了，感谢大佬！

**Comment by azmiao** [comment]
ok

**Comment by Baimotong** [comment]
大佬您好，最近发现在十连抽卡功能中抽到二星重炮会出问题
![image](https://github.com/azmiao/uma_plugin/assets/30062345/1265288e-33b2-492a-9557-7a8407dd0bc0)
经查发现将res\img\umamusume\uma_gacha\uma_pool.json里的重炮改成摩耶重炮后就正常了
![image](https://github.com/azmiao/uma_plugin/assets/30062345/c93e6054-63c3-441f-9133-06782601941a)
跟您反馈一下

**Comment by azmiao** [comment]
我有空看下哈，应该是wiki命名改了

**Comment by azmiao** [comment]
已更新，自测了下好像欸啥问题，有问题再反馈吧
