### ISSUE TITLE
1周年了，又该更新了

### ISSUE THREAD

**Issue by Yui-xy** [azmiao/uma_plugin#54]
技能模块提示拉取失败
马娘技能信息刷新失败：'NoneType' object has no attribute 'find'

**Comment by azmiao** [comment]
我尽量我尽量，最近上班有点忙2333

**Comment by azmiao** [comment]
哎，我这好像测试没有这个问题欸，你那能测试一下让我康康日志吗

**Comment by Yui-xy** [comment]
> 哎，我这好像测试没有这个问题欸，你那能测试一下让我康康日志吗
是我的问题，没注意到你2 mouth前更新过了2333

**Comment by azmiao** [comment]
> > 哎，我这好像测试没有这个问题欸，你那能测试一下让我康康日志吗
> > 是我的问题，没注意到你2 month前更新过了2333

欧克欧克，能用就好，那我先关闭issue了
