### ISSUE TITLE
Bot的任何消息都被风控

### ISSUE THREAD

**Issue by simpleYOTO** [azmiao/uma_plugin#56]
我尝试了3个账号，命令行可以看到Bot是有指令发送的，但是在cqhttp任何消息都会被风控发不出消息。但是我用nonebot2消息是不会被风控的。大佬有什么办法吗，感谢大佬指教

**Comment by azmiao** [comment]
你看下你现在的gocqhttp版本和马娘插件的版本

**Comment by simpleYOTO** [comment]
Bot我用的是你网站上的马娘整合精简版，gocqhttp有用1.10版本和最新版本

**Comment by simpleYOTO** [comment]
那个一键包还挺好用的，不过还是风控，可能我的小号都有问题了，也感谢大佬。

**Comment by azmiao** [comment]
https://www.594594.xyz/2022/03/05/uma_bot/
教程更新了，另外里面也提供了新的版本，如需要可以自取
