### ISSUE TITLE
更新后拉取技能报错惹

### ISSUE THREAD

**Issue by Yui-xy** [azmiao/uma_plugin#57]
使用命令“手动更新马娘技能”时报错“Expecting value: line 1 column 203285 (char 203284)”

可能是技能模块没有做国服适配的关系？

**Comment by azmiao** [comment]
貌似bwiki的[这个页面](https://wiki.biligame.com/umamusume/%E6%8A%80%E8%83%BD%E9%80%9F%E6%9F%A5%E8%A1%A8)的技能全没了，繁中和简中的页面倒是还在，等过段时间再看看他会不会恢复，另外暂时没有做单独查繁中或者简中的功能，目前仅是通用，后续可以添加

**Comment by azmiao** [comment]
哦貌似是技能太多展示不下了，页面显示也出问题了，我看看咋整

**Comment by azmiao** [comment]
先留了个评论，看看大佬们怎么改，之后我这插件再适配更新吧
![image](https://github.com/azmiao/uma_plugin/assets/54100327/a9a07b49-3fc4-4f57-8c88-68f4770267b4)

**Comment by azmiao** [comment]
已经联系大佬临时修改了wiki的页面展示内容，现在插件应该也正常了，你再手动更新一下试试

**Comment by Yui-xy** [comment]
可以了
