### ISSUE TITLE
繁中服10月节奏榜链接发生变化导致获取不到节奏榜

### ISSUE THREAD

**Issue by Yui-xy** [azmiao/uma_plugin#59]
看了一下目前繁中服节奏榜的链接是
![image](https://github.com/azmiao/uma_plugin/assets/109400934/70b033f3-e011-4550-81ed-00565806b4d4)
脚本貌似获取不到了

**Comment by azmiao** [comment]
巧了你手慢了，30分钟前我已经提交了代码了hhhhh🤣
