### ISSUE TITLE
指令可能有误

### ISSUE THREAD

**Issue by chenchenriver** [azmiao/uma_plugin#6]
![image](https://user-images.githubusercontent.com/93070768/157912178-4d9f9faa-6df9-4f33-9aa0-d7175790c1c4.png)
如果这个的是hoshinobot的话，该指令应该是启用 xxxxx而不是开启 xxxxx

**Comment by azmiao** [comment]
![IMG_20220312_013558](https://user-images.githubusercontent.com/54100327/157919493-0595acba-9bdf-4507-ac58-d83d50d0a41b.jpg)
您好，如图

**Comment by chenchenriver** [comment]
但是似乎使用原命令无效
![5227019F-3199-4DFA-8495-BD23CDB915C9](https://user-images.githubusercontent.com/93070768/157920610-1f68df3f-ed55-479c-945f-5c314d330261.jpeg)
![54996AB2-C8D9-4927-B102-2A2DCE935C6C](https://user-images.githubusercontent.com/93070768/157920625-0c915d91-855b-40bf-bb7f-af3b5aadbec3.jpeg)
使用星乃自带的启用命令以后有效。
我分析有可能是有其他插件相互冲突

**Comment by chenchenriver** [comment]
打扰了

**Comment by azmiao** [comment]
确实，应该是有什么插件命令不规范和command冲突了（
