### ISSUE TITLE
耐力值计算模块不能正常计算技能有无时的耐力。测试记录如下

### ISSUE THREAD

**Issue by LingEnd** [azmiao/uma_plugin#60]
澐酱 09:24:56
算耐力
属性：600 600 600 300 350
适应性：先马-S 芝-A 2400-A
干劲：绝好调 状况：良
固回：0 普回：1 金回：3

小栗栗 09:24:57
速度上限：600
耐力：600
力量：600
根性：300
智力：350
跑法：先马 - S
跑场：芝 - A
跑道：2400米 - A
天气：良 | 干劲：绝好调

序盘体力需求：497.3
中盘体力需求：1194.2
终盘体力需求：1512.0

本次携带了：
    - 0级的固有回体
    - 1个普通回体
    - 3个金回体

其中：
-每个普通回体回复42.7体力
    - 折合耐力：59.9
-每个金回体回复156.4体力
    - 折合耐力：219.7
-固有体力回复0.0体力
    - 折合耐力：0.0

汇总：
无回体技能的体力需求：3203.5
算上技能后的本马体力：3356.3

结论：
无回体技能的耐力需求：1128.6
算上技能后的本马耐力：1343.1

注：此数据取自根性下坡改版前的数据
实际需求比计算器结果要高不少，尤其是大赛
本计算器仅为能刚好正常跑完的耐力最低下限
数值为非常理想的情况，没有加速技能，因此仅供参考

澐酱 09:25:56
算耐力
属性：600 600 600 300 350
适应性：先马-S 芝-A 2000-A
干劲：绝好调 状况：良
固回：0 普回：1 金回：3

小栗栗 09:25:57
速度上限：600
耐力：600
力量：600
根性：300
智力：350
跑法：先马 - S
跑场：芝 - A
跑道：2000米 - A
天气：良 | 干劲：绝好调

序盘体力需求：429.7
中盘体力需求：974.6
终盘体力需求：1245.3

本次携带了：
    - 0级的固有回体
    - 1个普通回体
    - 3个金回体

其中：
-每个普通回体回复36.7体力
    - 折合耐力：51.5
-每个金回体回复134.4体力
    - 折合耐力：188.8
-固有体力回复0.0体力
    - 折合耐力：0.0

汇总：
无回体技能的体力需求：2649.7
算上技能后的本马体力：2884.3

结论：
无回体技能的耐力需求：912.5
算上技能后的本马耐力：1241.9

注：此数据取自根性下坡改版前的数据
实际需求比计算器结果要高不少，尤其是大赛
本计算器仅为能刚好正常跑完的耐力最低下限
数值为非常理想的情况，没有加速技能，因此仅供参考

澐酱 09:26:39
算耐力
属性：600 600 600 300 350
适应性：先马-S 芝-A 2000-A
干劲：绝好调 状况：良
固回：0 普回：1 金回：2

小栗栗 09:26:40
速度上限：600
耐力：600
力量：600
根性：300
智力：350
跑法：先马 - S
跑场：芝 - A
跑道：2000米 - A
天气：良 | 干劲：绝好调

序盘体力需求：429.7
中盘体力需求：974.6
终盘体力需求：1245.3

本次携带了：
    - 0级的固有回体
    - 1个普通回体
    - 2个金回体

其中：
-每个普通回体回复36.7体力
    - 折合耐力：51.5
-每个金回体回复134.4体力
    - 折合耐力：188.8
-固有体力回复0.0体力
    - 折合耐力：0.0

汇总：
无回体技能的体力需求：2649.7
算上技能后的本马体力：2749.8

结论：
无回体技能的耐力需求：912.5
算上技能后的本马耐力：1053.1

注：此数据取自根性下坡改版前的数据
实际需求比计算器结果要高不少，尤其是大赛
本计算器仅为能刚好正常跑完的耐力最低下限
数值为非常理想的情况，没有加速技能，因此仅供参考

澐酱 09:26:49
算耐力
属性：600 600 600 300 350
适应性：先马-S 芝-A 1600-A
干劲：绝好调 状况：良
固回：0 普回：1 金回：2

小栗栗 09:26:50
速度上限：600
耐力：600
力量：600
根性：300
智力：350
跑法：先马 - S
跑场：芝 - A
跑道：1600米 - A
天气：良 | 干劲：绝好调

序盘体力需求：365.2
中盘体力需求：763.9
终盘体力需求：988.5

本次携带了：
    - 0级的固有回体
    - 1个普通回体
    - 2个金回体

其中：
-每个普通回体回复30.7体力
    - 折合耐力：43.1
-每个金回体回复112.4体力
    - 折合耐力：157.9
-固有体力回复0.0体力
    - 折合耐力：0.0

汇总：
无回体技能的体力需求：2117.6
算上技能后的本马体力：2299.8

结论：
无回体技能的耐力需求：727.0
算上技能后的本马耐力：982.9

注：此数据取自根性下坡改版前的数据
实际需求比计算器结果要高不少，尤其是大赛
本计算器仅为能刚好正常跑完的耐力最低下限
数值为非常理想的情况，没有加速技能，因此仅供参考

澐酱 09:27:04
算耐力
属性：600 600 600 300 350
适应性：先马-S 芝-A 2000-A
干劲：绝好调 状况：良
固回：0 普回：1 金回：0

小栗栗 09:27:05
速度上限：600
耐力：600
力量：600
根性：300
智力：350
跑法：先马 - S
跑场：芝 - A
跑道：2000米 - A
天气：良 | 干劲：绝好调

序盘体力需求：429.7
中盘体力需求：974.6
终盘体力需求：1245.3

本次携带了：
    - 0级的固有回体
    - 1个普通回体
    - 0个金回体

其中：
-每个普通回体回复36.7体力
    - 折合耐力：51.5
-每个金回体回复134.4体力
    - 折合耐力：188.8
-固有体力回复0.0体力
    - 折合耐力：0.0

汇总：
无回体技能的体力需求：2649.7
算上技能后的本马体力：2481.0

结论：
无回体技能的耐力需求：912.5
算上技能后的本马耐力：675.5

注：此数据取自根性下坡改版前的数据
实际需求比计算器结果要高不少，尤其是大赛
本计算器仅为能刚好正常跑完的耐力最低下限
数值为非常理想的情况，没有加速技能，因此仅供参考

**Comment by LingEnd** [comment]
另一种测试结果：
结果展示的无技能耐力高于有技能


速度上限：600
耐力：600
力量：600
根性：300
智力：350
跑法：先马 - S
跑场：芝 - A
跑道：2000米 - A
天气：良 | 干劲：绝好调

序盘体力需求：429.7
中盘体力需求：974.6
终盘体力需求：1245.3

本次携带了：
    - 0级的固有回体
    - 1个普通回体
    - 0个金回体

其中：
-每个普通回体回复36.7体力
    - 折合耐力：51.5
-每个金回体回复134.4体力
    - 折合耐力：188.8
-固有体力回复0.0体力
    - 折合耐力：0.0

汇总：
无回体技能的体力需求：2649.7
算上技能后的本马体力：2481.0

结论：
无回体技能的耐力需求：912.5
算上技能后的本马耐力：675.5

注：此数据取自根性下坡改版前的数据
实际需求比计算器结果要高不少，尤其是大赛
本计算器仅为能刚好正常跑完的耐力最低下限
数值为非常理想的情况，没有加速技能，因此仅供参考

**Comment by azmiao** [comment]
我一会先看看，太久了都忘了完了2333

**Comment by azmiao** [comment]
> 另一种测试结果： 结果展示的无技能耐力高于有技能
> 
> 速度上限：600 耐力：600 力量：600 根性：300 智力：350 跑法：先马 - S 跑场：芝 - A 跑道：2000米 - A 天气：良 | 干劲：绝好调
> 
> 序盘体力需求：429.7 中盘体力需求：974.6 终盘体力需求：1245.3
> 
> 本次携带了： - 0级的固有回体 - 1个普通回体 - 0个金回体
> 
> 其中： -每个普通回体回复36.7体力 - 折合耐力：51.5 -每个金回体回复134.4体力 - 折合耐力：188.8 -固有体力回复0.0体力 - 折合耐力：0.0
> 
> 汇总： 无回体技能的体力需求：2649.7 算上技能后的本马体力：2481.0
> 
> 结论： 无回体技能的耐力需求：912.5 算上技能后的本马耐力：675.5
> 
> 注：此数据取自根性下坡改版前的数据 实际需求比计算器结果要高不少，尤其是大赛 本计算器仅为能刚好正常跑完的耐力最低下限 数值为非常理想的情况，没有加速技能，因此仅供参考

我看了下感觉好像没问题吧，需求耐力912，实际算上技能回复的耐力后总耐力只有675，你看看是不是我写的不太好理解

**Comment by azmiao** [comment]
刚刚的提交改了一波描述，你看下现在应该好理解一点了，8418bb7a0d8d2b276d095354288748fa69094ed8

**Comment by LingEnd** [comment]
我发现的问题是他里面需求耐力和算上技能后的需求按理来说是前者大于后者，但是上述几条中有些是后者反而大于前者的感觉有些不和逻辑，好像我学的技能越多奈丽旭求越高一样，此外有一条记录中明明没有标注有学习金回体技能，回复却计算出了金回体技能的耐力回复量
没有标注却计算了金回体的记录
![image](https://github.com/azmiao/uma_plugin/assets/86486177/048bfd7b-b489-437c-aae3-44e8cd2167da)
有技能耐力需求反而大于无技能的记录
![image](https://github.com/azmiao/uma_plugin/assets/86486177/364001b6-829f-4c34-9fa6-2061aa24bf97)

**Comment by azmiao** [comment]
哦，你说这个啊，这个是我没有写清楚，无回体的耐力需求是要跑完这场比赛需要的耐力；然后算上技能后的本马耐力，是指你的马娘吃完所有回体技能后，实际真正拥有的耐力值；如果马娘实际耐力＞需要的耐力，说明能跑完；如果实际耐力＜需要的耐力，说明跑不完。

另外一个问题，金回体个数为0也会计算回复耐力值，会写出单个技能回复的耐力，但那个不会参与前面的体力计算，只是方便在跑不完的情况下，根据回复耐力值，自己合理安排学习技能

注：代码昨天已经更新了相关描述，可能会更容易理解一点，你更新下代码看看？

**Comment by LingEnd** [comment]
好的~感谢解惑😘😘😘
