### ISSUE TITLE
国服新闻有bug

### ISSUE THREAD

**Issue by kafenut** [azmiao/uma_plugin#62]
# 获取新闻更新
async def news_broadcast_bili():
    news_list = await sort_news()
    current_dir = os.path.join(os.path.dirname(__file__), 'prev_time_tw.yml')
    with open(current_dir, 'r', encoding="UTF-8") as f:
        init_time = str(f.read())
    init_time = datetime.datetime.strptime(init_time, '%Y-%m-%d %H:%M:%S')
    msg = '◎◎ B服马娘新闻更新 ◎◎\n'
    for news in news_list:
        prev_time = datetime.datetime.strptime(news.news_time, '%Y-%m-%d %H:%M:%S')
        if (init_time >= prev_time):
            break
        else:
            news_time = datetime.datetime.strptime(news.news_time, '%Y-%m-%d %H:%M:%S')
            msg += '\n' + str(news_time) + '\n' + news.news_title + '\n' + news.news_url + '\n'

    for news in news_list:
        set_time = news.news_time
        break
    with open(current_dir, 'w', encoding="UTF-8") as f:
        f.write(str(set_time))
    return msg
    
这个函数write的是prev_time_tw.yml

**Comment by azmiao** [comment]
哦，复制的时候写错了23333

**Comment by azmiao** [comment]
直接改了下，未测试，如果还有问题的话再反馈下我再仔细看看
