### ISSUE TITLE
相性榜功能 个别马娘相性查不到的问题

### ISSUE THREAD

**Issue by dreamerMJJ** [azmiao/uma_plugin#63]
![image](https://github.com/azmiao/uma_plugin/assets/92427687/a68e520e-49db-4299-b010-fa66ab0b09d6)
偶然发现的 目前只发现这俩

**Comment by azmiao** [comment]
我一会看看哈

**Comment by azmiao** [comment]
已修复，你可以更新下试试

**Comment by dreamerMJJ** [comment]
可以了 辛苦了
