### ISSUE TITLE
错误数据？

### ISSUE THREAD

**Issue by HMScygnet** [azmiao/uma_plugin#7]
um_info/config.json中有一条为
"xxxx03": {
        "id": 7553,
        "jp_name": "xxxx03",
        "category": "umamusume",
        "voice": false,
        "uniform_img": "https://umamusume.jp/app/wp-content/uploads/2022/03/ba7ff9fbf1e32dc48eb346efc1ab1906.png",
        "winning_suit_img": "",
        "original_img": "",
        "cv": "",
        "bir": "",
        "height": "",
        "weight": "",
        "measurements": "",
        "sns_icon": "https://umamusume.jp/app/wp-content/uploads/2022/03/b67eeedcd27da5671b34e325dd450286.png",
        "prev_en_name": "yaenomuteki",
        "next_en_name": "mejirobright",
        "cn_name": "",
        "grass": "",
        "mud": "",
        "short": "",
        "mile": "",
        "middle": "",
        "long": "",
        "run_away": "",
        "first": "",
        "center": "",
        "chase": ""
    },
的数据会导致key error报错
![error](https://user-images.githubusercontent.com/65561426/159111102-cc9af2cb-3cad-4c15-af8e-c3d3742663db.png)
删除后可正常使用

**Comment by HMScygnet** [comment]
注：查任何角色都会有这个KeyError:'xxxx03'的报错

**Comment by azmiao** [comment]
请更新到最新版，然后再手动更新马娘数据一次即可。这里解释一下原因，xxxx03是鹤丸刚志的id，昨天官网更新了吧xxxx03换成了真实的英文名，但更新数据的时候没有删除旧的数据，我昨晚已经修复了这个BUG，详情可以看commit。

**Comment by azmiao** [comment]
当然你现在能用就不用再更新数据了，直接更新到最新版就OK了，以后讲道理不会再遇到这样的问题了

**Comment by azmiao** [comment]
先关闭issue了，有问题再反馈吧
