### ISSUE TITLE
抽卡功能的支援卡十选二卡池可以支持选两张卡作为up目标吗

### ISSUE THREAD

**Issue by Baimotong** [azmiao/uma_plugin#72]
如图，每次的目标都不一样
![image](https://github.com/azmiao/uma_plugin/assets/30062345/24a3fc35-a412-40e6-bf6a-bc842ce9e5c6)
![image](https://github.com/azmiao/uma_plugin/assets/30062345/b4258e7d-8bb6-4a89-9ae5-bac0841165a9)

**Comment by azmiao** [comment]
目前设计是随机的，要改应该也是可以改的，我最近暂时较忙，后续有空可以看看，如果你这边闲的话可以改改提交个pr😆

**Comment by azmiao** [comment]
基本功能开发完成，等待合并

**Comment by azmiao** [comment]
合并完成

**Comment by azmiao** [comment]
是这样的：

**Comment by azmiao** [comment]
马娘的那个卡池因为插件没设计抽满破，所以好像暂时也不用选择目标，毕竟感觉大多数人应该也不会为了抽满而花个好几井吧哈哈

**Comment by Baimotong** [comment]
了解了，再次感谢！
