### ISSUE TITLE
马娘卡池信息更新失败：'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by jojoyDuck** [azmiao/uma_plugin#74]
无法使用马娘卡池与卡池更新
<img width="446" alt="屏幕截图 2024-08-31 170444" src="https://github.com/user-attachments/assets/67ba9caa-319b-4c08-800e-05f00df9f7e2">

**Comment by azmiao** [comment]
经排查，旧的卡池图片缺失导致的，这边尝试规避下
![image](https://github.com/user-attachments/assets/30878a52-1422-4a41-9e13-b44045fe6971)

**Comment by jojoyDuck** [comment]
OK了，赞美dalao

**Comment by jojoyDuck** [comment]
现在出现了所有s@bot的指令无法使用的情况，控制台里对指令也没有响应
![image](https://github.com/user-attachments/assets/dbb3f931-6164-4b71-9d55-25266045f15c)

**Comment by azmiao** [comment]
> 现在出现了所有@bot的指令无法使用的情况，控制台里对指令也没有响应 ![image](https://private-user-images.githubusercontent.com/101507242/363417343-dbb3f931-6164-4b71-9d55-25266045f15c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTI0NTMsIm5iZiI6MTcyNTExMjE1MywicGF0aCI6Ii8xMDE1MDcyNDIvMzYzNDE3MzQzLWRiYjNmOTMxLTYxNjQtNGI3MS05ZDU1LTI1MjY2MDQ1ZjE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxMzQ5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2Q5YTFiNjc5ZWM5Nzk4ZjM1YzhlNTYwMzIzOTJjMTRmNTliYmQzYjZhNmY1YjgzM2EzYjhjYTI0Y2ZmYTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.klpkSdvpi7C_lw-bNhx4dduOOMutzIa8T2bzzM5Fa0g)

检查一下hoshino启动的时候有没有报错

**Comment by jojoyDuck** [comment]
没看见有报错
![image](https://github.com/user-attachments/assets/71222690-8dc5-43e8-89ec-818b508d67f5)

**Comment by azmiao** [comment]
那就奇怪了，看看有没有其他插件对命令造成冲突了？

**Comment by jojoyDuck** [comment]
其他插件都关掉了依旧没有用）

**Comment by azmiao** [comment]
> 其他插件都关掉了依旧没有用）

那你要不重启一下hoshino然后发个命令，吧启动到发命令期间所有日志都发出来看看？

**Comment by jojoyDuck** [comment]
[2024-08-31 23:35:43,373 config] WARNING: Not found config of "uma_plugin"
[2024-08-31 23:35:43,373 config] WARNING: Not found config of "botmanage"
[2024-08-31 23:35:44,436 hoshino] INFO: 【马娘插件】启动时检查更新...
[2024-08-31 23:35:45,311 hoshino] INFO: 【马娘插件】更新检查完成...
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.umamusume_news"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_almanac"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_comic"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_compatibility"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_endurance"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_face"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_gacha_v2"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_info"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_skills"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_support_chart"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_target"
[2024-08-31 23:35:45,311 nonebot] INFO: Succeeded to import "hoshino.modules.uma_plugin.uma_tasks"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.alert"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.billing"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.broadcast"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.data_cleaner"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.feedback"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.get_cqcode"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_invite"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_leave"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.help"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.ls"
[2024-08-31 23:35:45,327 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.service_manage"
[2024-08-31 23:35:45,327 nonebot] INFO: Running on 127.0.0.1:2333
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:2333 (CTRL + C to quit)
[2024-08-31 23:35:45,343 nonebot] INFO: Scheduler started
[2024-08-31 23:35:45,343] Running on http://127.0.0.1:2333 (CTRL + C to quit)
[2024-08-31 23:35:46,000] 127.0.0.1:62194 GET /ws/ 1.1 101 - 0
[2024-08-31 23:35:55,413 nonebot] INFO: Self: 3658145178, Message 2115237130 from 2898472906@[群:982596093]: '多来点霰弹子弹就更爽了'
[2024-08-31 23:36:01,792 nonebot] INFO: Self: 3658145178, Message 1124023641 from 1574729112@[群:698057453]: '[CQ:reply,id=1873843464][CQ:at,qq=2737491916,name=若葉睦]感觉你是大妹子'
[2024-08-31 23:36:01,792 nonebot] INFO: Self: 3658145178, Message 1982350245 from 1574729112@[群:698057453]: '[CQ:image,file=016F338123974C2F8C0C7A3FD5B791FE.png,subType=1,url=https://multimedia.nt.qq.com.cn/download?appid=1407&amp;fileid=CgoxNTc0NzI5MTEyEhQvcC5D46ZKOzystcjnqKMjAIjk6xjExAMg_woorryKt8efiANQgL2jAQ&amp;spec=0&amp;rkey=CAQSKAB6JWENi5LMhhDdprvdR-WvM-l6F0fcI8XWISHLOSMl3TnlVUsDRJo,file_size=57924]'

**Comment by azmiao** [comment]
看起来没啥问题诶，你发个“@bot更新马娘卡池”试试，看看日志有啥东西吗，另外你的上报服务器端用的什么，是gocqhttp还是llonebot还是napcat还是lagrange

**Comment by jojoyDuck** [comment]
llonebot,输入以后日志上啥也没有
![image](https://github.com/user-attachments/assets/1cb426b6-e32b-4038-b227-888da0b555c6)

**Comment by azmiao** [comment]
> llonebot,输入以后日志上啥也没有，但不加@bot是可以更新的 ![image](https://private-user-images.githubusercontent.com/101507242/363424320-1cb426b6-e32b-4038-b227-888da0b555c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjAyMDksIm5iZiI6MTcyNTExOTkwOSwicGF0aCI6Ii8xMDE1MDcyNDIvMzYzNDI0MzIwLTFjYjQyNmI2LWUzMmItNDAzOC1iMjI3LTg4OGRhMGI1NTVjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNTU4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDJlYjY5ZjBmNmJlNzcwYzU3ODc1OWM2YTA3ODM2ZTNlMjY1NWU5YzhiMGUyOWJiMDQ5OGIyZDQ1ZWU0Mzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nMCCX8pJ1wpsnpxmFZHUNbfGX8gsPJd_XkyqiNszd5c)

你这个好像不太对，@正常收到的应该是[CQ:at开头的，@人不能复制不然不算@的

**Comment by azmiao** [comment]
> 现在出现了所有@bot的指令无法使用的情况，控制台里对指令也没有响应 ![image](https://private-user-images.githubusercontent.com/101507242/363417343-dbb3f931-6164-4b71-9d55-25266045f15c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjAyMDksIm5iZiI6MTcyNTExOTkwOSwicGF0aCI6Ii8xMDE1MDcyNDIvMzYzNDE3MzQzLWRiYjNmOTMxLTYxNjQtNGI3MS05ZDU1LTI1MjY2MDQ1ZjE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNTU4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzFkMmRmZjcyYmU4OWZiMjZkYjFiNGNjYzcxOTIwN2FiMGRhZDI1MmViNjlkYjJkZDkxNDZlYTJiNjIyZWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SRc3R_HwnXe8Qk_GwSy1iyVsuPXKxNdcFc3rFZ_iq-U)

比如这个就是正常的@，但是你这个@里多了个name参数不知道对nonebot解析的时候有没有影响，正常的原版@应该行如`[CQ:at,qq=23333333333]`这样的

**Comment by azmiao** [comment]
> 现在出现了所有@bot的指令无法使用的情况，控制台里对指令也没有响应 ![image](https://private-user-images.githubusercontent.com/101507242/363417343-dbb3f931-6164-4b71-9d55-25266045f15c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjAyMDksIm5iZiI6MTcyNTExOTkwOSwicGF0aCI6Ii8xMDE1MDcyNDIvMzYzNDE3MzQzLWRiYjNmOTMxLTYxNjQtNGI3MS05ZDU1LTI1MjY2MDQ1ZjE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNTU4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzFkMmRmZjcyYmU4OWZiMjZkYjFiNGNjYzcxOTIwN2FiMGRhZDI1MmViNjlkYjJkZDkxNDZlYTJiNjIyZWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SRc3R_HwnXe8Qk_GwSy1iyVsuPXKxNdcFc3rFZ_iq-U)

比如这个就是正常的@，但是你这个@里多了个name参数不知道对nonebot解析的时候有没有影响，正常的原版@应该行如`[CQ:at,qq=23333333333]`这样的

**Comment by jojoyDuck** [comment]
不复制依旧是这样的
![image](https://github.com/user-attachments/assets/d94b23ee-7b4f-42ee-ad17-9e48f01c710a)

**Comment by azmiao** [comment]
llonebot最近有更新什么东西吗

**Comment by jojoyDuck** [comment]
在我使用llonebot之后只更新过一次
![image](https://github.com/user-attachments/assets/d4887f54-ca8d-4986-b9c2-b862719333ce)

**Comment by azmiao** [comment]
请问你那方便试试旧版吗

**Comment by azmiao** [comment]
时候不早了，我先睡了，明早起来再帮你看看哈

**Comment by azmiao** [comment]
你去`HoshinoBot/hoshino/config/__bot__.py`文件里把debug模式打开看看`DEBUG = True`

**Comment by jojoyDuck** [comment]
![image](https://github.com/user-attachments/assets/03fd179b-bea9-4869-a108-efd1f6b39479)

**Comment by azmiao** [comment]
> ![image](https://private-user-images.githubusercontent.com/101507242/363459465-03fd179b-bea9-4869-a108-efd1f6b39479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjY4NTQsIm5iZiI6MTcyNTE2NjU1NCwicGF0aCI6Ii8xMDE1MDcyNDIvMzYzNDU5NDY1LTAzZmQxNzliLWJlYTktNDg2OS1hMTA4LWVmZDFmNmIzOTQ3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNDU1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDMyMGRjYmQ0OWU5ODc1MzI4NWM0ZGQwMTU1ZDM4MjQ4MTVhNTA4YjYxOWFmYTY5YzQxMTUxNzBjNTY1YTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hF7Rh_r_hMyuRh5tywPb53N4rB38pCabcMeqzRyX5no)

那确实是llonebot那边给@加了个name，导致nonebot获取的时候获取不到@的人，正常的Parsing command里面应该是`('马娘十连',)`这样的

**Comment by azmiao** [comment]
看看你的llonebot的日志吧，hoshino的debug模式可以关掉了

**Comment by jojoyDuck** [comment]
2024/9/1 13:21:49 process pid 5012 

2024/9/1 13:21:49 [info] (3658145178) | app LLOneBot/3.31.2

2024/9/1 13:21:49 [info] (3658145178) | onebot Trying to connect to the websocket server: ws://127.0.0.1:2333/ws/

2024/9/1 13:21:49 [error] (3658145178) | onebot Error: connect ECONNREFUSED 127.0.0.1:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

2024/9/1 13:21:49 [info] (3658145178) | onebot The websocket connection: ws://127.0.0.1:2333/ws/ closed, trying reconnecting...

2024/9/1 13:21:50 [info] (3658145178) | app 好友列表变动 7

2024/9/1 13:21:50 [info] (3658145178) | app 好友列表变动 7

2024/9/1 13:21:52 [info] (3658145178) | onebot Trying to connect to the websocket server: ws://127.0.0.1:2333/ws/

2024/9/1 13:21:52 [error] (3658145178) | onebot Error: connect ECONNREFUSED 127.0.0.1:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

2024/9/1 13:21:52 [info] (3658145178) | onebot The websocket connection: ws://127.0.0.1:2333/ws/ closed, trying reconnecting...

2024/9/1 13:21:54 [info] (3658145178) | app 好友列表变动 34

2024/9/1 13:21:55 [info] (3658145178) | onebot Trying to connect to the websocket server: ws://127.0.0.1:2333/ws/

2024/9/1 13:21:55 [error] (3658145178) | onebot Error: connect ECONNREFUSED 127.0.0.1:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

2024/9/1 13:21:55 [info] (3658145178) | onebot The websocket connection: ws://127.0.0.1:2333/ws/ closed, trying reconnecting...

2024/9/1 13:21:58 开始检查 FFmpeg C:\ffmpeg\bin\ffmpeg.exe 

2024/9/1 13:22:00 [info] (3658145178) | onebot Trying to connect to the websocket server: ws://127.0.0.1:2333/ws/

2024/9/1 13:22:00 [error] (3658145178) | onebot Error: connect ECONNREFUSED 127.0.0.1:2333
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

2024/9/1 13:22:00 [info] (3658145178) | onebot The websocket connection: ws://127.0.0.1:2333/ws/ closed, trying reconnecting...

2024/9/1 13:22:01 FFmpeg is installed. 

2024/9/1 13:22:01 查询 LLOneBot 错误信息  

2024/9/1 13:22:03 [info] (3658145178) | onebot Trying to connect to the websocket server: ws://127.0.0.1:2333/ws/

2024/9/1 13:22:03 [info] (3658145178) | onebot Connected to the websocket server: ws://127.0.0.1:2333/ws/

2024/9/1 13:22:03 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:06 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:09 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:12 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:15 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:18 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:19 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ message

2024/9/1 13:22:21 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:24 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:27 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:30 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:33 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:36 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:39 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:42 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:45 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:48 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:51 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:54 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:22:57 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:23:00 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:23:01 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ message

2024/9/1 13:23:03 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:23:06 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:23:09 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:23:11 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ message

2024/9/1 13:23:12 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:23:15 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ meta_event

2024/9/1 13:23:16 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ message

2024/9/1 13:23:16 [info] (3658145178) | onebot WebSocket 事件上报 ws://127.0.0.1:2333/ws/ message

**Comment by azmiao** [comment]
没有详细日志吗

**Comment by jojoyDuck** [comment]
暂时删去了only_to_me=True，在不用@的情况下可以使用了

**Comment by azmiao** [comment]
> 暂时删去了only_to_me=True，在不用@的情况下可以使用了

嗯，可以先这样用
